"""alter column product_per_year

Revision ID: 1516fc94f9a1
Revises: 74b5e2c8ee5d
Create Date: 2018-06-14 10:26:42.850046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1516fc94f9a1'
down_revision = '74b5e2c8ee5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('product_per_year', sa.Integer(), nullable=False))
    op.drop_column('form_data', 'number_product_per_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('number_product_per_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('form_data', 'product_per_year')
    # ### end Alembic commands ###
