"""add column data to form_data table

Revision ID: 1a466d8ad294
Revises: f87dc9a08cae
Create Date: 2018-06-14 13:24:03.134056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1a466d8ad294'
down_revision = 'f87dc9a08cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_data', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_data', 'date')
    # ### end Alembic commands ###
