"""add alerts table

Revision ID: 599a5cdf7986
Revises: 1a466d8ad294
Create Date: 2018-06-18 17:13:31.296588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '599a5cdf7986'
down_revision = '1a466d8ad294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('reminder_interval', sa.Integer(), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_campaign_id'), 'alerts', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_campaign_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
