"""add form_data table

Revision ID: 5db67954199b
Revises: f3b3cc014a75
Create Date: 2018-06-13 11:48:29.620356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db67954199b'
down_revision = 'f3b3cc014a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('number_product_per_year', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_data_form_id'), 'form_data', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_data_recipient_id'), 'form_data', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_data_recipient_id'), table_name='form_data')
    op.drop_index(op.f('ix_form_data_form_id'), table_name='form_data')
    op.drop_table('form_data')
    # ### end Alembic commands ###
