"""add column to form_filled table

Revision ID: f87dc9a08cae
Revises: 1516fc94f9a1
Create Date: 2018-06-14 12:30:44.932007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f87dc9a08cae'
down_revision = '1516fc94f9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_filled', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_filled', 'date')
    # ### end Alembic commands ###
