"""add campaigns_recipents table

Revision ID: fe75ac99dba2
Revises: 38303c64b9f0
Create Date: 2018-06-13 12:55:32.729358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'fe75ac99dba2'
down_revision = '38303c64b9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns_recipients',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'recipient_id')
    )
    op.create_index(op.f('ix_campaigns_recipients_campaign_id'), 'campaigns_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaigns_recipients_recipient_id'), 'campaigns_recipients', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_recipients_recipient_id'), table_name='campaigns_recipients')
    op.drop_index(op.f('ix_campaigns_recipients_campaign_id'), table_name='campaigns_recipients')
    op.drop_table('campaigns_recipients')
    # ### end Alembic commands ###
